# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yi Yan's blog
email: yiyan@u.nus.edu
description: > # this means to ignore newlines until "baseurl:"
  CS3281/2 blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://garbanzos.github.io" # the base hostname & protocol for your site
github_username:  garbanzos

# Build settings
markdown: kramdown
